name: Example workflow for MTA
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: carlosthe19916/windup-action@master
        id: rhamt
        with:
          target: eap7
          input: simple-sample-app.ear
          output: simple-sample-app.ear.report
          additional-command-line-arguments: "--sourceMode" #(Optional) You can define all commands available in Migration Toolkit for Applications
